import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";

import styles from "../styles/Home.module.css";

import React, { FormEventHandler, useEffect } from "react";
//import { captchaSettings } from "reactjs-captcha";

const Captcha = dynamic(
  () => import("reactjs-captcha").then((mod) => mod.Captcha),
  {
    ssr: false,
  }
);

// const captchaSettings = dynamic(
//   () => import("reactjs-captcha").then((mod) => mod.captchaSettings),
//   {
//     ssr: false,
//   }
// );

const CaptchaForm = () => {
  let captcha: any;
  const onSubmit: FormEventHandler = async (e) => {
    console.log("io", captcha);
    const userEnteredCaptchaCode = captcha.getUserEnteredCaptchaCode();
    const captchaId = captcha.getCaptchaId();
    const postData = {
      userEnteredCaptchaCode: userEnteredCaptchaCode,
      captchaId: captchaId,
    };
    console.log("postData", postData);
    const result = await fetch("/api/submit", {
      method: "POST",
      body: JSON.stringify(postData),
      headers: { "Content-Type": "application/json; charset=utf-8" },
    }).then((r) => {
      try {
        return r.json();
      } catch (e) {
        console.log(r.statusText);
        console.log(r.text());
        console.log(e);
      }
    });
    console.log("result", result);
    if (result.data && result.data.success === false) {
      console.log("NOK");
      captcha.reloadImage();
    } else {
      console.log("oKIKKKKK");
    }
    e.preventDefault();
  };
  useEffect(() => {
    const initCaptcha = async () => {
      const captchaSettings = (await import("reactjs-captcha")).captchaSettings;
      console.log("captchaSettings", captchaSettings);
      if (captchaSettings.set) {
        captchaSettings.set({
          captchaEndpoint: "/api/simple-captcha-endpoint",
        });
      }
    };
    if (captcha) initCaptcha();
  }, [captcha]);
  return (
    <section id="main-content" style={{ textAlign: "center" }}>
      <form id="captchaForm" method="POST" onSubmit={onSubmit}>
        <Captcha
          //@ts-ignore
          captchaStyleName="captchaFR"
          ref={(instance: any) => {
            captcha = instance;
          }}
        />
        <br />
        <label>
          <input id="captchaFormulaireExtInput" type="text" />
        </label>
        <br />
        <button type="submit" id="submitButton">
          Validate
        </button>
      </form>
    </section>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CatchEtat demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://api.gouv.fr/les-api/api-captchetat">CaptchEtat</a>{" "}
          demo
        </h1>
        <br />
        <br />
        <br />
        <br />

        <CaptchaForm />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/socialgouv"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by SocialGouv
        </a>
      </footer>
    </div>
  );
};

export default Home;
